export assimp_DIR="/usr/local/lib/cmake/assimp-5.3"

cmake -S . -B build \
-DOGRE_BUILD_SAMPLES=OFF \
-DOGRE_BUILD_LIBS_AS_FRAMEWORKS=OFF \
-DOGRE_BUILD_COMPONENT_CSHARP=OFF \
-DOGRE_BUILD_COMPONENT_JAVA=OFF \
-DOGRE_BUILD_COMPONENT_PYTHON=OFF 
-DOGRE_BUILD_COMPONENT_TERRAIN=OFF \
-DOGRE_BUILD_COMPONENT_OVERLAY_IMGUI=OFF \
-DOGRE_BUILD_PLUGIN_CG=OFF \
-DOGRE_BUILD_PLUGIN_PCZ=OFF \
-DOGRE_CONFIG_ENABLE_ASTC=OFF \
-DOGRE_CONFIG_ENABLE_ETC=OFF \
-DOGRE_CONFIG_ENABLE_PVRTC=OFF \
-DOGRE_CONFIG_ENABLE_DDS=OFF 

cmake --build build
cmake --install build

